from sfaira_extension.versions.topology_versions.human.celltype.celltypemarker import CELLTYPEMARKER_TOPOLOGIES
from sfaira_extension.versions.topology_versions.human.celltype.celltypemlp import CELLTYPEMLP_TOPOLOGIES
